import type { Event, Opportunity, SessionDetail } from "../types";

const baseDate = new Date();

function addDays(days: number, hours = 0) {
  const date = new Date(baseDate);
  date.setDate(date.getDate() + days);
  date.setHours(hours, 0, 0, 0);
  return date.toISOString();
}

export const demoSessions: SessionDetail[] = [
  {
    id: 1,
    title: "Introduction à la finance d'entreprise",
    description: "Session de révision sur les concepts clés de la finance de marché et d'entreprise.",
    scheduled_at: addDays(1, 10),
    duration_minutes: 90,
    capacity: 20,
    meet_link: "https://meet.google.com/demo-session-1",
    is_cancelled: false,
    subject_id: 1,
    tutor_id: "demo-tutor-1",
    created_at: addDays(-2, 12),
    tutor: {
      id: "demo-tutor-1",
      full_name: "Sarra Ben Ali",
      email: "sarra@example.com",
      bio: "Tuteur en finance",
      avatar_url: null,
      role: "tutor",
      is_active: true,
      created_at: addDays(-30, 8),
    },
    subject: {
      id: 1,
      name: "Finance",
      description: "Bases financières",
      created_at: addDays(-30, 8),
    },
    participant_count: 13,
    average_rating: 4.8,
  },
  {
    id: 2,
    title: "Marketing digital et stratégie",
    description: "Comprendre le funnel, le contenu et la mesure de performance.",
    scheduled_at: addDays(3, 14),
    duration_minutes: 75,
    capacity: 16,
    meet_link: "https://meet.google.com/demo-session-2",
    is_cancelled: false,
    subject_id: 2,
    tutor_id: "demo-tutor-2",
    created_at: addDays(-1, 11),
    tutor: {
      id: "demo-tutor-2",
      full_name: "Youssef Trabelsi",
      email: "youssef@example.com",
      bio: "Tuteur en marketing",
      avatar_url: null,
      role: "tutor",
      is_active: true,
      created_at: addDays(-40, 8),
    },
    subject: {
      id: 2,
      name: "Marketing",
      description: "Marketing et stratégie",
      created_at: addDays(-40, 8),
    },
    participant_count: 9,
    average_rating: 4.6,
  },
  {
    id: 3,
    title: "Comptabilité analytique: exercices",
    description: "Travail guidé sur les exercices les plus fréquents d'examen.",
    scheduled_at: addDays(5, 9),
    duration_minutes: 120,
    capacity: 24,
    meet_link: null,
    is_cancelled: false,
    subject_id: 3,
    tutor_id: "demo-tutor-3",
    created_at: addDays(-1, 15),
    tutor: {
      id: "demo-tutor-3",
      full_name: "Meriem Khelifi",
      email: "meriem@example.com",
      bio: "Tuteur en comptabilité",
      avatar_url: null,
      role: "tutor",
      is_active: true,
      created_at: addDays(-20, 8),
    },
    subject: {
      id: 3,
      name: "Comptabilité",
      description: "Comptabilité analytique",
      created_at: addDays(-20, 8),
    },
    participant_count: 21,
    average_rating: 4.9,
  },
];

export const demoEvents: Event[] = [
  {
    id: 1,
    type: "workshop",
    title: "Workshop Startup Challenge",
    description: "Idées, business model et pitch avec des intervenants du secteur.",
    host_user_id: "demo-admin-1",
    subject_id: null,
    major_id: 1,
    academic_year_id: 3,
    delivery_mode: "onsite",
    location_text: "Amphithéâtre A",
    meeting_url: null,
    starts_at: addDays(2, 15),
    ends_at: addDays(2, 17),
    capacity: 120,
    created_at: addDays(-4, 10),
    participant_count: 84,
  },
  {
    id: 2,
    type: "networking",
    title: "Forum Stage & Emploi",
    description: "Rencontre avec des recruteurs et alumni de l'IHEC.",
    host_user_id: "demo-admin-1",
    subject_id: null,
    major_id: 1,
    academic_year_id: 2,
    delivery_mode: "onsite",
    location_text: "Hall principal",
    meeting_url: null,
    starts_at: addDays(6, 9),
    ends_at: addDays(6, 12),
    capacity: 200,
    created_at: addDays(-5, 9),
    participant_count: 150,
  },
  {
    id: 3,
    type: "formation",
    title: "Formation IA pour étudiants",
    description: "Découverte pratique des usages de l'IA pour les études et projets.",
    host_user_id: "demo-admin-1",
    subject_id: null,
    major_id: 2,
    academic_year_id: 3,
    delivery_mode: "hybrid",
    location_text: "Salle multimédia",
    meeting_url: "https://meet.google.com/demo-event-3",
    starts_at: addDays(8, 13),
    ends_at: addDays(8, 15),
    capacity: 60,
    created_at: addDays(-2, 16),
    participant_count: 46,
  },
];

export const demoOpportunities: Opportunity[] = [
  {
    id: 1,
    title: "Stage Data Analyst",
    company: "Nexa Consulting",
    description: "Stage de 3 mois pour soutenir l'analyse commerciale et reporting.",
    opportunity_type: "internship",
    location: "Tunis",
    is_remote: false,
    apply_url: "https://example.com/apply/data-analyst",
    deadline: addDays(12, 12),
    is_published: true,
    created_by: "demo-admin-1",
    created_at: addDays(-7, 11),
  },
  {
    id: 2,
    title: "Part-time assistant marketing",
    company: "Mediabox",
    description: "Support campagnes et contenu pour réseaux sociaux.",
    opportunity_type: "job",
    location: "Lac 2",
    is_remote: true,
    apply_url: "https://example.com/apply/marketing-assistant",
    deadline: addDays(9, 12),
    is_published: true,
    created_by: "demo-admin-1",
    created_at: addDays(-6, 11),
  },
  {
    id: 3,
    title: "Compétition business plan",
    company: "IHEC StartLab",
    description: "Concours d'innovation pour projets étudiants.",
    opportunity_type: "competition",
    location: "Campus IHEC",
    is_remote: false,
    apply_url: null,
    deadline: addDays(18, 12),
    is_published: true,
    created_by: "demo-admin-1",
    created_at: addDays(-4, 13),
  },
];
